# Generated by Django 6.0.3 on 2026-03-19 18:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_delivered_order_delivery_fee_and_more'),
        ('products', '0002_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Zone name (e.g., Gasabo Zone)', max_length=100, null=True)),
                ('districts', models.CharField(blank=True, help_text='Comma-separated list of districts', max_length=255, null=True)),
                ('base_fee', models.DecimalField(blank=True, decimal_places=2, default=2000, help_text='Base delivery fee in RWF', max_digits=10, null=True)),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, default=50000, help_text='Orders above this amount get free delivery', max_digits=10, null=True)),
                ('estimated_delivery_hours', models.IntegerField(blank=True, default=24, help_text='Estimated delivery time in hours', null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Whether this zone is currently active', null=True)),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, help_text='Product rating (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('delivery_rating', models.IntegerField(blank=True, help_text='Delivery service rating (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Review comment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Review submission date', null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, help_text='Whether review is approved for display', null=True)),
            ],
            options={
                'verbose_name': 'Order Review',
                'verbose_name_plural': 'Order Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, help_text='Unique transaction identifier', max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount in RWF', max_digits=10, null=True)),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash on Delivery'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('card', 'Credit/Debit Card')], help_text='Payment method used', max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Current payment status', max_length=20, null=True)),
                ('provider_response', models.JSONField(blank=True, help_text='Raw response from payment provider', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When payment was initiated', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Recipient phone number', max_length=15, null=True)),
                ('message', models.TextField(blank=True, help_text='SMS content', null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', help_text='Delivery status', max_length=20, null=True)),
                ('type', models.CharField(blank=True, choices=[('order_confirmation', 'Order Confirmation'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('status_update', 'Status Update')], help_text='Type of notification', max_length=50, null=True)),
                ('provider_response', models.TextField(blank=True, help_text='Response from SMS provider', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When SMS was created', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When SMS was actually sent', null=True)),
            ],
            options={
                'verbose_name': 'SMS Notification',
                'verbose_name_plural': 'SMS Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], help_text='Status at this update', max_length=50, null=True)),
                ('location', models.CharField(blank=True, help_text='Location description', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed update description', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Update timestamp', null=True)),
            ],
            options={
                'verbose_name': 'Tracking Update',
                'verbose_name_plural': 'Tracking Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['created_at'], 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AddField(
            model_name='order',
            name='actual_delivery',
            field=models.DateTimeField(blank=True, help_text='Actual delivery date and time', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current latitude for tracking', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='current_location',
            field=models.CharField(blank=True, help_text='Current location description', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current longitude for tracking', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional email for notifications', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, help_text='Estimated delivery date and time', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Special instructions for delivery', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, editable=False, help_text='Unique order identifier (EMG-XXXXXXXX)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', help_text='Current payment status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sms_notification_sent',
            field=models.BooleanField(blank=True, default=False, help_text='Whether SMS notification has been sent', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sms_opt_in',
            field=models.BooleanField(blank=True, default=True, help_text='Customer opted in for SMS updates', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Public tracking number for customers', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update date and time', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Item addition date', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at time of purchase', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, help_text='Delivery address', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='Kigali', help_text='City (defaults to Kigali)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Order creation date and time', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=2000, help_text='Delivery fee in RWF', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, choices=[('Gasabo', 'Gasabo'), ('Kicukiro', 'Kicukiro'), ('Nyarugenge', 'Nyarugenge')], help_text='Kigali district for delivery', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of customer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash on Delivery', 'Cash on Delivery'), ('MTN Mobile Money', 'MTN Mobile Money'), ('Airtel Money', 'Airtel Money')], default='Cash on Delivery', help_text='Selected payment method', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Current order status', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Customer who placed the order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Parent order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product ordered', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, help_text='Quantity ordered', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_number'], name='orders_orde_trackin_04edf9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='order',
            field=models.OneToOneField(blank=True, help_text='Order being reviewed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Customer who wrote the review', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(blank=True, help_text='Order being paid for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order'),
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Related order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='orders.order'),
        ),
        migrations.AddField(
            model_name='trackingupdate',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order being tracked', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='orders.order'),
        ),
        migrations.AddField(
            model_name='trackingupdate',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this update', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trackingupdate',
            index=models.Index(fields=['order', '-created_at'], name='orders_trac_order_i_bd2b72_idx'),
        ),
    ]
