# Generated by Django 6.0.2 on 2026-04-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_deliveryzone_orderreview_payment_smsnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_locked',
            field=models.BooleanField(default=False, help_text='Whether stock has already been reserved for this order'),
        ),
    ]
