# Generated by Django 6.0.2 on 2026-04-20 08:52

from django.db import migrations, models
import uuid


def populate_existing_skus(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.filter(sku__isnull=True):
        product.sku = f"SKU-{uuid.uuid4().hex[:8].upper()}"
        product.save(update_fields=['sku'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.RunPython(populate_existing_skus, migrations.RunPython.noop),
    ]
