# Generated by Codex on 2026-04-20

from django.db import migrations, models


def infer_product_category(name, description=''):
    haystack = f"{name} {description}".lower()
    keyword_map = (
        ('electronics', ('phone', 'laptop', 'headphone', 'speaker', 'watch', 'tablet', 'tv', 'camera', 'charger', 'computer')),
        ('fashion', ('shoe', 'shirt', 'dress', 'jean', 'jacket', 'fashion', 'clothing', 'bag', 'sandal')),
        ('home', ('chair', 'table', 'bed', 'home', 'kitchen', 'pot', 'plate', 'lamp', 'sofa', 'curtain')),
        ('beauty', ('soap', 'lotion', 'cream', 'makeup', 'perfume', 'beauty', 'shampoo', 'conditioner')),
        ('office', ('book', 'pen', 'printer', 'office', 'notebook', 'paper', 'school', 'desk')),
        ('groceries', ('rice', 'sugar', 'tea', 'coffee', 'milk', 'bread', 'grocer', 'food', 'drink')),
        ('health', ('vitamin', 'health', 'mask', 'sanitizer', 'medicine', 'supplement', 'wellness')),
        ('sports', ('ball', 'fitness', 'sport', 'bike', 'helmet', 'gym', 'training')),
        ('accessories', ('case', 'cover', 'cable', 'accessory', 'wallet', 'belt')),
    )

    for category, keywords in keyword_map:
        if any(keyword in haystack for keyword in keywords):
            return category

    return 'general'


def populate_existing_categories(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        product.category = infer_product_category(product.name or '', product.description or '')
        product.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(
                choices=[
                    ('general', 'General'),
                    ('electronics', 'Electronics'),
                    ('fashion', 'Fashion'),
                    ('home', 'Home & Living'),
                    ('beauty', 'Beauty & Care'),
                    ('office', 'Office & School'),
                    ('groceries', 'Groceries'),
                    ('health', 'Health & Wellness'),
                    ('sports', 'Sports & Outdoors'),
                    ('accessories', 'Accessories'),
                ],
                db_index=True,
                default='general',
                max_length=40,
            ),
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name']},
        ),
        migrations.RunPython(populate_existing_categories, migrations.RunPython.noop),
    ]
